services:
   minio:
      image: minio/minio
      command: server /data --console-address ":19000"
      ports:
        - "9000:9000"
        - "19000:19000"
      environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123